name: Publish Python distribution to PyPI 
on: push
jobs:
  build:
    name: Build distribution 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user

        
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      id: gitversion
      with:
        useConfigFile: true

    - name: Set Version 
      run: echo "__version__ = \"${{ steps.gitversion.outputs.semVer }}\"" > ./jupyternetes_models/_version.py

    - name: Build a binary wheel and a source tarball
      run: python3 -m build

    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/